[versions]
java-target = "17"
java-toolchain = "22"

fgp = "0.14.0"

kotlin = "2.0.0"
coroutines = "1.8.1"
android-gradle = "8.5.0"
ksp="2.0.0-1.0.22"
anvil = "2.5.0-beta09"
paparazzi = "1.3.4-fl01"
licensee = "1.11.0"
crashlytics-gradle = "3.0.2"
dependency-analysis = "1.32.0"
develocity = "3.17.5"
gradle-toolchain = "0.8.0"
publish = "0.29.0"
dokka = "1.9.20"

clikt = "4.4.0"
ktlint = "1.3.0"

junit = "4.13.2"
truth = "1.4.3"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlin-gradle-annotations = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-annotations", version.ref = "kotlin" }
kotlin-native-utils = { module = "org.jetbrains.kotlin:kotlin-native-utils", version.ref = "kotlin" }

android-gradle = { module = "com.android.tools.build:gradle-api", version.ref = "android-gradle" }
ksp-gradle = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin",  version.ref = "ksp" }
anvil-gradle = { module = "com.squareup.anvil:gradle-plugin", version.ref = "anvil" }
paparazzi-gradle = { module = "com.freeletics.fork.paparazzi:paparazzi-gradle-plugin", version.ref = "paparazzi" }

licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version.ref = "licensee" }
crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics-gradle" }

dependency-analysis = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependency-analysis" }

develocity = { module = "com.gradle:develocity-gradle-plugin", version.ref = "develocity" }
gradle-toolchain = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "gradle-toolchain" }

publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish"}

clikt = { module = "com.github.ajalt.clikt:clikt-jvm", version.ref = "clikt" }
ktlint-rule-engine = { module = "com.pinterest.ktlint:ktlint-rule-engine", version.ref = "ktlint" }
ktlint-rule-engine-core = { module = "com.pinterest.ktlint:ktlint-rule-engine-core", version.ref = "ktlint" }
ktlint-rules = { module = "com.pinterest.ktlint:ktlint-ruleset-standard", version.ref = "ktlint" }

junit = { module = "junit:junit", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
fgp-root = { id = "com.freeletics.gradle.root", version.ref = "fgp" }
fgp-settings = { id = "com.freeletics.gradle.settings", version.ref = "fgp" }
fgp-gradle = { id = "com.freeletics.gradle.gradle", version.ref = "fgp" }
fgp-jvm = { id = "com.freeletics.gradle.jvm", version.ref = "fgp" }
fgp-publish = { id = "com.freeletics.gradle.publish.oss", version.ref = "fgp" }

android = { id = "com.android.application", version.ref = "android-gradle" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
