[versions]
java-target = "11"
java-toolchain = "19"

fgp = "0.9.0"

gradle-api = "8.4"
kotlin = "1.9.22"
coroutines = "1.7.3"
android-gradle = "8.2.1"
android-gradle-common = "31.2.1"
jb-compose="1.5.11"
ksp="1.9.22-1.0.16"
anvil = "2.4.8"
moshix = "0.25.1"
paparazzi = "1.3.1-fl02"
licensee = "1.8.0"
crashlytics-gradle = "2.9.8"
dependency-analysis = "1.28.0"
bestpractices = "0.10"
gradle-enterprise = "3.16.1"
gradle-toolchain = "0.7.0"
gr8 = "0.10"
publish = "0.26.0"
dokka = "1.9.10"

clikt = "4.2.2"
ktlint = "0.50.0"

junit = "4.13.2"
truth = "1.2.0"

[libraries]
gradle-api = { module = "dev.gradleplugins:gradle-api", version.ref = "gradle-api" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlin-native-utils = { module = "org.jetbrains.kotlin:kotlin-native-utils", version.ref = "kotlin" }

android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "android-gradle" }
android-tools-common = { module = "com.android.tools:common", version.ref = "android-gradle-common" }

compose-gradle = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jb-compose" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin",  version.ref = "ksp" }
anvil-gradle = { module = "com.squareup.anvil:gradle-plugin", version.ref = "anvil" }
moshix-gradle = { module = "dev.zacsweers.moshix:moshi-gradle-plugin", version.ref = "moshix" }
paparazzi-gradle = { module = "com.freeletics.fork.paparazzi:paparazzi-gradle-plugin", version.ref = "paparazzi" }

licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version.ref = "licensee" }
crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics-gradle" }

dependency-analysis = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependency-analysis" }

gradle-enterprise = { module = "com.gradle:gradle-enterprise-gradle-plugin", version.ref = "gradle-enterprise" }
gradle-toolchain = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "gradle-toolchain" }

gr8 = { module = "com.gradleup:gr8-plugin", version.ref = "gr8" }
publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish"}

clikt = { module = "com.github.ajalt.clikt:clikt-jvm", version.ref = "clikt" }
ktlint-rule-engine = { module = "com.pinterest.ktlint:ktlint-rule-engine", version.ref = "ktlint" }
ktlint-rule-engine-core = { module = "com.pinterest.ktlint:ktlint-rule-engine-core", version.ref = "ktlint" }
ktlint-rules = { module = "com.pinterest.ktlint:ktlint-ruleset-standard", version.ref = "ktlint" }

junit = { module = "junit:junit", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
fgp-root = { id = "com.freeletics.gradle.root", version.ref = "fgp" }
fgp-settings = { id = "com.freeletics.gradle.settings", version.ref = "fgp" }
fgp-gradle = { id = "com.freeletics.gradle.gradle", version.ref = "fgp" }
fgp-jvm = { id = "com.freeletics.gradle.jvm", version.ref = "fgp" }
fgp-publish = { id = "com.freeletics.gradle.publish.oss", version.ref = "fgp" }

android = { id = "com.android.application", version.ref = "android-gradle" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
bestpractices = { id = "com.autonomousapps.plugin-best-practices-plugin", version.ref = "bestpractices" }
gr8 = { id = "com.gradleup.gr8", version.ref = "gr8" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
