[versions]
java-target = "11"
java-toolchain = "17"
java-gradle = "17"

fl-gradle = "0.2.0"

gradle-api = "8.0.2"
kotlin = "1.8.10"
android-gradle = "8.0.0-beta05"
ksp="1.8.10-1.0.9"
anvil = "2.4.4"
moshix = "0.21.0"
paparazzi = "1.2.1-fl01"
licensee = "1.6.0"
crashlytics-gradle = "2.9.4"
dependency-analysis = "1.19.0"
bestpractices = "0.9"
gradle-enterprise = "3.12.4"
gradle-toolchain = "0.4.0"
gr8 = "0.7"
publish = "0.24.0"

junit = "4.13.2"
truth = "1.1.3"

[libraries]
gradle-api = { module = "dev.gradleplugins:gradle-api", version.ref = "gradle-api" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }

android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "android-gradle" }

ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin",  version.ref = "ksp" }
anvil-gradle = { module = "com.squareup.anvil:gradle-plugin", version.ref = "anvil" }
moshix-gradle = { module = "dev.zacsweers.moshix:moshi-gradle-plugin", version.ref = "moshix" }

licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version.ref = "licensee" }
crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics-gradle" }

dependency-analysis = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependency-analysis" }

gradle-enterprise = { module = "com.gradle:gradle-enterprise-gradle-plugin", version.ref = "gradle-enterprise" }
gradle-toolchain = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "gradle-toolchain" }

gr8 = { module = "com.gradleup:gr8-plugin", version.ref = "gr8" }
publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish"}

junit = { module = "junit:junit", version.ref = "junit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
fl-root = { id = "com.freeletics.gradle.root", version.ref = "fl-gradle" }
fl-settings = { id = "com.freeletics.gradle.settings", version.ref = "fl-gradle" }
fl-gradle = { id = "com.freeletics.gradle.common.gradle", version.ref = "fl-gradle" }
fl-jvm = { id = "com.freeletics.gradle.common.jvm", version.ref = "fl-gradle" }
fl-publish = { id = "com.freeletics.gradle.common.publish.oss", version.ref = "fl-gradle" }

android = { id = "com.android.application", version.ref = "android-gradle" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }
bestpractices = { id = "com.autonomousapps.plugin-best-practices-plugin", version.ref = "bestpractices" }
gr8 = { id = "com.gradleup.gr8", version.ref = "gr8" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
